# Generated by Django 5.1 on 2024-11-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('delivery_address', models.TextField()),
                ('selected_plan', models.CharField(choices=[('Basic', 'Basic Plan (Solo)'), ('Balanced', 'Balanced Plan (2 People)'), ('Family', 'Family Plan (4 People)')], default='Basic', max_length=50)),
                ('dietary_preference', models.CharField(choices=[('Vegan', 'Vegetables'), ('Non_Vegan', 'Non-Vegan'), ('No_Preference', 'No Preference')], default='No_Preference', max_length=50)),
                ('Optional_Add_ons', models.TextField()),
            ],
        ),
    ]
