# Generated by Django 5.1 on 2024-11-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinfo',
            name='dietary_preference',
            field=models.CharField(choices=[('Vegan', 'Vegan'), ('Non_Vegan', 'Non-Vegan'), ('No_Preference', 'No Preference')], default='No_Preference', max_length=50),
        ),
    ]
