# Generated by Django 5.1 on 2024-11-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_generalinfo_dietary_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinfo',
            name='Optional_Add_ons',
            field=models.TextField(blank=True, null=True),
        ),
    ]
