# Generated by Django 5.1 on 2024-11-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_generalinfo_optional_add_ons'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalinfo',
            name='token_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
